CREATE TABLE message (
  id INTEGER PRIMARY KEY NOT NULL,
  mailbox VARCHAR NOT NULL,
  content VARCHAR NOT NULL,
  timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  read INTEGER NOT NULL DEFAULT FALSE
);
